export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const TODO_ITEM_ADD = 'TODO_ITEM_ADD';

export const TODO_ITEMS_REQUEST = 'TODO_ITEMS_REQUEST';
export const TODO_ITEMS_SUCCESS = 'TODO_ITEMS_SUCCESS';
export const TODO_ITEMS_ERROR = 'TODO_ITEMS_ERROR';
